# cspell:disable
[project]
authors = [{ name = "ThePhaseless", email = "kukubaorch@gmail.com" }]
license = { text = "LICENSE" }
requires-python = "<4.0,>=3.12"
name = "Byparr"
version = "0.1.0"
description = "API for getting cookies for Cloudflare challenges"
readme = "README.md"
dependencies = [
    "beautifulsoup4==4.13.3",
    "fastapi[standard]==0.115.8",
    "psutil==6.1.1",
    "pyautogui==0.9.54",
    "pydantic==2.10.6",
    "seleniumbase==4.34.6",
    "uvicorn==0.34.0",
]
urls = { repository = "https://github.com/ThePhaseless/Byparr" }

[dependency-groups]
test = [
    "httpx==0.28.1",
    "pytest==8.3.4",
    "pytest-asyncio==0.25.3",
    "pytest-progress==1.3.0",
    "pytest-retry==1.7.0",
    "pytest-xdist==3.6.1",
]
dev = ["deptry==0.23.0", "ruff==0.9.4"]

[tool.deptry.per_rule_ignores]
DEP002 = ["pyautogui"]

[tool.ruff.lint]
ignore = [
    "D203",
    "D212",
    "D100",
    "D400",
    "EM101",
    "S101",
    "D104",
    "ANN201",
    "TD003",
    "PLR0913",
    "ERA001",
    "COM812",
    "ISC001",
    "TC003",
    "TC002",
    "TC001",
    "TD002",
    "E501",
    "D101",
    "G004",
    "ANN001",
    "ANN204",
    "ANN206",
]
select = ["ALL"]
extend-safe-fixes = ["D415"]

[tool.pytest]
log_cli = "True"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
